# coding: utf-8

"""
    Bungie.Net API

    These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.  # noqa: E501

    OpenAPI spec version: 2.3.6
    Contact: support@bungie.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class SingleComponentResponseOfDestinyItemComponent(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'data': 'DestinyItemComponent',
        'privacy': 'int'
    }

    attribute_map = {
        'data': 'data',
        'privacy': 'privacy'
    }

    def __init__(self, data=None, privacy=None):  # noqa: E501
        """SingleComponentResponseOfDestinyItemComponent - a model defined in OpenAPI"""  # noqa: E501

        self._data = None
        self._privacy = None
        self.discriminator = None

        if data is not None:
            self.data = data
        if privacy is not None:
            self.privacy = privacy

    @property
    def data(self):
        """Gets the data of this SingleComponentResponseOfDestinyItemComponent.  # noqa: E501


        :return: The data of this SingleComponentResponseOfDestinyItemComponent.  # noqa: E501
        :rtype: DestinyItemComponent
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this SingleComponentResponseOfDestinyItemComponent.


        :param data: The data of this SingleComponentResponseOfDestinyItemComponent.  # noqa: E501
        :type: DestinyItemComponent
        """

        self._data = data

    @property
    def privacy(self):
        """Gets the privacy of this SingleComponentResponseOfDestinyItemComponent.  # noqa: E501


        :return: The privacy of this SingleComponentResponseOfDestinyItemComponent.  # noqa: E501
        :rtype: int
        """
        return self._privacy

    @privacy.setter
    def privacy(self, privacy):
        """Sets the privacy of this SingleComponentResponseOfDestinyItemComponent.


        :param privacy: The privacy of this SingleComponentResponseOfDestinyItemComponent.  # noqa: E501
        :type: int
        """

        self._privacy = privacy

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SingleComponentResponseOfDestinyItemComponent):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
