# coding: utf-8

"""
    Bungie.Net API

    These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.  # noqa: E501

    OpenAPI spec version: 2.3.6
    Contact: support@bungie.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class DestinyHistoricalStatsValuePair(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'value': 'float',
        'display_value': 'str'
    }

    attribute_map = {
        'value': 'value',
        'display_value': 'displayValue'
    }

    def __init__(self, value=None, display_value=None):  # noqa: E501
        """DestinyHistoricalStatsValuePair - a model defined in OpenAPI"""  # noqa: E501

        self._value = None
        self._display_value = None
        self.discriminator = None

        if value is not None:
            self.value = value
        if display_value is not None:
            self.display_value = display_value

    @property
    def value(self):
        """Gets the value of this DestinyHistoricalStatsValuePair.  # noqa: E501

        Raw value of the statistic  # noqa: E501

        :return: The value of this DestinyHistoricalStatsValuePair.  # noqa: E501
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this DestinyHistoricalStatsValuePair.

        Raw value of the statistic  # noqa: E501

        :param value: The value of this DestinyHistoricalStatsValuePair.  # noqa: E501
        :type: float
        """

        self._value = value

    @property
    def display_value(self):
        """Gets the display_value of this DestinyHistoricalStatsValuePair.  # noqa: E501

        Localized formated version of the value.  # noqa: E501

        :return: The display_value of this DestinyHistoricalStatsValuePair.  # noqa: E501
        :rtype: str
        """
        return self._display_value

    @display_value.setter
    def display_value(self, display_value):
        """Sets the display_value of this DestinyHistoricalStatsValuePair.

        Localized formated version of the value.  # noqa: E501

        :param display_value: The display_value of this DestinyHistoricalStatsValuePair.  # noqa: E501
        :type: str
        """

        self._display_value = display_value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DestinyHistoricalStatsValuePair):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
