# coding: utf-8

"""
    Bungie.Net API

    These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.  # noqa: E501

    OpenAPI spec version: 2.3.6
    Contact: support@bungie.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class DestinyStat(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'stat_hash': 'int',
        'value': 'int',
        'maximum_value': 'int'
    }

    attribute_map = {
        'stat_hash': 'statHash',
        'value': 'value',
        'maximum_value': 'maximumValue'
    }

    def __init__(self, stat_hash=None, value=None, maximum_value=None):  # noqa: E501
        """DestinyStat - a model defined in OpenAPI"""  # noqa: E501

        self._stat_hash = None
        self._value = None
        self._maximum_value = None
        self.discriminator = None

        if stat_hash is not None:
            self.stat_hash = stat_hash
        if value is not None:
            self.value = value
        if maximum_value is not None:
            self.maximum_value = maximum_value

    @property
    def stat_hash(self):
        """Gets the stat_hash of this DestinyStat.  # noqa: E501

        The hash identifier for the Stat. Use it to look up the DestinyStatDefinition for static data about the stat.  # noqa: E501

        :return: The stat_hash of this DestinyStat.  # noqa: E501
        :rtype: int
        """
        return self._stat_hash

    @stat_hash.setter
    def stat_hash(self, stat_hash):
        """Sets the stat_hash of this DestinyStat.

        The hash identifier for the Stat. Use it to look up the DestinyStatDefinition for static data about the stat.  # noqa: E501

        :param stat_hash: The stat_hash of this DestinyStat.  # noqa: E501
        :type: int
        """

        self._stat_hash = stat_hash

    @property
    def value(self):
        """Gets the value of this DestinyStat.  # noqa: E501

        The current value of the Stat.  # noqa: E501

        :return: The value of this DestinyStat.  # noqa: E501
        :rtype: int
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this DestinyStat.

        The current value of the Stat.  # noqa: E501

        :param value: The value of this DestinyStat.  # noqa: E501
        :type: int
        """

        self._value = value

    @property
    def maximum_value(self):
        """Gets the maximum_value of this DestinyStat.  # noqa: E501

        The highest possible value for the stat, if we were able to compute it. (I wouldn't necessarily trust this value right now. I would like to improve its calculation in later iterations of the API. Consider this a placeholder for desired future functionality)  # noqa: E501

        :return: The maximum_value of this DestinyStat.  # noqa: E501
        :rtype: int
        """
        return self._maximum_value

    @maximum_value.setter
    def maximum_value(self, maximum_value):
        """Sets the maximum_value of this DestinyStat.

        The highest possible value for the stat, if we were able to compute it. (I wouldn't necessarily trust this value right now. I would like to improve its calculation in later iterations of the API. Consider this a placeholder for desired future functionality)  # noqa: E501

        :param maximum_value: The maximum_value of this DestinyStat.  # noqa: E501
        :type: int
        """

        self._maximum_value = maximum_value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DestinyStat):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
