# coding: utf-8

"""
    Bungie.Net API

    These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.  # noqa: E501

    OpenAPI spec version: 2.3.6
    Contact: support@bungie.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class DestinyActivityPlaylistItemDefinition(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'activity_hash': 'int',
        'direct_activity_mode_hash': 'int',
        'direct_activity_mode_type': 'int',
        'activity_mode_hashes': 'list[int]',
        'activity_mode_types': 'list[int]'
    }

    attribute_map = {
        'activity_hash': 'activityHash',
        'direct_activity_mode_hash': 'directActivityModeHash',
        'direct_activity_mode_type': 'directActivityModeType',
        'activity_mode_hashes': 'activityModeHashes',
        'activity_mode_types': 'activityModeTypes'
    }

    def __init__(self, activity_hash=None, direct_activity_mode_hash=None, direct_activity_mode_type=None, activity_mode_hashes=None, activity_mode_types=None):  # noqa: E501
        """DestinyActivityPlaylistItemDefinition - a model defined in OpenAPI"""  # noqa: E501

        self._activity_hash = None
        self._direct_activity_mode_hash = None
        self._direct_activity_mode_type = None
        self._activity_mode_hashes = None
        self._activity_mode_types = None
        self.discriminator = None

        if activity_hash is not None:
            self.activity_hash = activity_hash
        self.direct_activity_mode_hash = direct_activity_mode_hash
        self.direct_activity_mode_type = direct_activity_mode_type
        if activity_mode_hashes is not None:
            self.activity_mode_hashes = activity_mode_hashes
        if activity_mode_types is not None:
            self.activity_mode_types = activity_mode_types

    @property
    def activity_hash(self):
        """Gets the activity_hash of this DestinyActivityPlaylistItemDefinition.  # noqa: E501

        The hash identifier of the Activity that can be played. Use it to look up the DestinyActivityDefinition.  # noqa: E501

        :return: The activity_hash of this DestinyActivityPlaylistItemDefinition.  # noqa: E501
        :rtype: int
        """
        return self._activity_hash

    @activity_hash.setter
    def activity_hash(self, activity_hash):
        """Sets the activity_hash of this DestinyActivityPlaylistItemDefinition.

        The hash identifier of the Activity that can be played. Use it to look up the DestinyActivityDefinition.  # noqa: E501

        :param activity_hash: The activity_hash of this DestinyActivityPlaylistItemDefinition.  # noqa: E501
        :type: int
        """

        self._activity_hash = activity_hash

    @property
    def direct_activity_mode_hash(self):
        """Gets the direct_activity_mode_hash of this DestinyActivityPlaylistItemDefinition.  # noqa: E501

        If this playlist entry had an activity mode directly defined on it, this will be the hash of that mode.  # noqa: E501

        :return: The direct_activity_mode_hash of this DestinyActivityPlaylistItemDefinition.  # noqa: E501
        :rtype: int
        """
        return self._direct_activity_mode_hash

    @direct_activity_mode_hash.setter
    def direct_activity_mode_hash(self, direct_activity_mode_hash):
        """Sets the direct_activity_mode_hash of this DestinyActivityPlaylistItemDefinition.

        If this playlist entry had an activity mode directly defined on it, this will be the hash of that mode.  # noqa: E501

        :param direct_activity_mode_hash: The direct_activity_mode_hash of this DestinyActivityPlaylistItemDefinition.  # noqa: E501
        :type: int
        """

        self._direct_activity_mode_hash = direct_activity_mode_hash

    @property
    def direct_activity_mode_type(self):
        """Gets the direct_activity_mode_type of this DestinyActivityPlaylistItemDefinition.  # noqa: E501

        If the playlist entry had an activity mode directly defined on it, this will be the enum value of that mode.  # noqa: E501

        :return: The direct_activity_mode_type of this DestinyActivityPlaylistItemDefinition.  # noqa: E501
        :rtype: int
        """
        return self._direct_activity_mode_type

    @direct_activity_mode_type.setter
    def direct_activity_mode_type(self, direct_activity_mode_type):
        """Sets the direct_activity_mode_type of this DestinyActivityPlaylistItemDefinition.

        If the playlist entry had an activity mode directly defined on it, this will be the enum value of that mode.  # noqa: E501

        :param direct_activity_mode_type: The direct_activity_mode_type of this DestinyActivityPlaylistItemDefinition.  # noqa: E501
        :type: int
        """
        allowed_values = [0, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 29, 30, 31, 32, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77]  # noqa: E501
        if direct_activity_mode_type not in allowed_values:
            raise ValueError(
                "Invalid value for `direct_activity_mode_type` ({0}), must be one of {1}"  # noqa: E501
                .format(direct_activity_mode_type, allowed_values)
            )

        self._direct_activity_mode_type = direct_activity_mode_type

    @property
    def activity_mode_hashes(self):
        """Gets the activity_mode_hashes of this DestinyActivityPlaylistItemDefinition.  # noqa: E501

        The hash identifiers for Activity Modes relevant to this entry.  # noqa: E501

        :return: The activity_mode_hashes of this DestinyActivityPlaylistItemDefinition.  # noqa: E501
        :rtype: list[int]
        """
        return self._activity_mode_hashes

    @activity_mode_hashes.setter
    def activity_mode_hashes(self, activity_mode_hashes):
        """Sets the activity_mode_hashes of this DestinyActivityPlaylistItemDefinition.

        The hash identifiers for Activity Modes relevant to this entry.  # noqa: E501

        :param activity_mode_hashes: The activity_mode_hashes of this DestinyActivityPlaylistItemDefinition.  # noqa: E501
        :type: list[int]
        """

        self._activity_mode_hashes = activity_mode_hashes

    @property
    def activity_mode_types(self):
        """Gets the activity_mode_types of this DestinyActivityPlaylistItemDefinition.  # noqa: E501

        The activity modes - if any - in enum form. Because we can't seem to escape the enums.  # noqa: E501

        :return: The activity_mode_types of this DestinyActivityPlaylistItemDefinition.  # noqa: E501
        :rtype: list[int]
        """
        return self._activity_mode_types

    @activity_mode_types.setter
    def activity_mode_types(self, activity_mode_types):
        """Sets the activity_mode_types of this DestinyActivityPlaylistItemDefinition.

        The activity modes - if any - in enum form. Because we can't seem to escape the enums.  # noqa: E501

        :param activity_mode_types: The activity_mode_types of this DestinyActivityPlaylistItemDefinition.  # noqa: E501
        :type: list[int]
        """

        self._activity_mode_types = activity_mode_types

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DestinyActivityPlaylistItemDefinition):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
