# coding: utf-8

"""
    Bungie.Net API

    These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.  # noqa: E501

    OpenAPI spec version: 2.3.6
    Contact: support@bungie.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class DestinyComponentType(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    DESTINY_COMPONENT_TYPE__0 = "0"
    DESTINY_COMPONENT_TYPE__100 = "100"
    DESTINY_COMPONENT_TYPE__101 = "101"
    DESTINY_COMPONENT_TYPE__102 = "102"
    DESTINY_COMPONENT_TYPE__103 = "103"
    DESTINY_COMPONENT_TYPE__104 = "104"
    DESTINY_COMPONENT_TYPE__105 = "105"
    DESTINY_COMPONENT_TYPE__200 = "200"
    DESTINY_COMPONENT_TYPE__201 = "201"
    DESTINY_COMPONENT_TYPE__202 = "202"
    DESTINY_COMPONENT_TYPE__203 = "203"
    DESTINY_COMPONENT_TYPE__204 = "204"
    DESTINY_COMPONENT_TYPE__205 = "205"
    DESTINY_COMPONENT_TYPE__300 = "300"
    DESTINY_COMPONENT_TYPE__301 = "301"
    DESTINY_COMPONENT_TYPE__302 = "302"
    DESTINY_COMPONENT_TYPE__303 = "303"
    DESTINY_COMPONENT_TYPE__304 = "304"
    DESTINY_COMPONENT_TYPE__305 = "305"
    DESTINY_COMPONENT_TYPE__306 = "306"
    DESTINY_COMPONENT_TYPE__307 = "307"
    DESTINY_COMPONENT_TYPE__308 = "308"
    DESTINY_COMPONENT_TYPE__400 = "400"
    DESTINY_COMPONENT_TYPE__401 = "401"
    DESTINY_COMPONENT_TYPE__402 = "402"
    DESTINY_COMPONENT_TYPE__500 = "500"
    DESTINY_COMPONENT_TYPE__600 = "600"
    DESTINY_COMPONENT_TYPE__700 = "700"
    DESTINY_COMPONENT_TYPE__800 = "800"
    DESTINY_COMPONENT_TYPE__900 = "900"

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
    }

    attribute_map = {
    }

    def __init__(self):  # noqa: E501
        """DestinyComponentType - a model defined in OpenAPI"""  # noqa: E501
        self.discriminator = None

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DestinyComponentType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
